### ISSUE TITLE
Fix around asciidoctor

### ISSUE THREAD

**Issue by uga-rosa** [tani/glance-vim#11]
https://github.com/tani/vim-glance/blob/082a35a9df24e40f0fd9786486119270720296a9/denops/glance/asciidoc.ts#L1

https://github.com/fardjad/deno-asciidoctor

`deno-asciidoctor` is public archived. It would be better to use `npm:asciidoctor@3.0.2`.

Also, deno lint prohibits explicit any by default; you should set the type imported from asciidoctor, or at least disable no-explicit-any.

https://lint.deno.land/?q=any

**Comment by tani** [comment]
Thank you! I solve this issue with 'npm:@asciidoctor/core' !
