### ISSUE TITLE
Couldn't load a font configuration in `g:glance#stylesheet`

### ISSUE THREAD

**Issue by peacock0803sz** [tani/glance-vim#16]
## Screenshot

https://github.com/user-attachments/assets/0b6236aa-bb6a-44d0-9fa6-44f8d9ab7bfa

## Expected Behavior

Renders with sans-serif style fonts
It works with other properties (`margin` and `border`), so is the wrong CSS selector for `font-family` ...?

## Environment Versions

denops.vim: commit `3a38e08`
vim-glance: commit `e645073`

```bash
$ nvim -V1 -v
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713773202

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/aqafkzaksbm4zk0343qi44xxlw6hvywn-neovim-unwrapped-0.10.2/share/nvim
"

Run :checkhealth for more info
$ deno --version
deno 2.0.2 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

## Step to Reproduce

Create those tow files:

`.vimrc`:
```vim
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/vim-glance

let g:glance#server_open = v:false
let g:glance#stylesheet =<< END
html, body, #viewer {
  border: none;
  margin: 0.5rem;
  font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif !important;
}
END
```

`example.md`: (Escaped the Nested Code Block)
```md
# Example Document

## This is a Heading 2

- list item1
- list item2
- list item3

### Code Sample

\```python
print("Hello World!!")
\```
```

**Comment by peacock0803sz** [comment]
UPDATE: Founded a typo `g:glance#styleseet` (correct: `g:glance#stylesheet`), but still not working the font configuration after fixing the typo...

**Comment by tani** [comment]
AH, there still is a typo. `font-famiiy` should be `font-family`.

**Comment by peacock0803sz** [comment]
@tani Oh, sorry! I fixed but not it isn't working well 😕

**Comment by tani** [comment]
I see. I will check it again.

**Comment by peacock0803sz** [comment]
humm... It looks the `g:glance#stylesheet` value was inside of the `<iframe>` tag 👀

**Comment by peacock0803sz** [comment]
humm... It looks the `g:glance#stylesheet` value was inside of the `<iframe>` tag 👀 
![image](https://github.com/user-attachments/assets/2d306ee7-5459-4602-81f4-a52fb9e9ad9a)
![CleanShot 2024-11-07 at 12 51 06](https://github.com/user-attachments/assets/f185df37-4dd9-4f28-affb-403c49147e00)

**Comment by tani** [comment]
<img width="1046" alt="Screenshot 2024-11-07 at 12 50 07" src="https://github.com/user-attachments/assets/5ff5440f-6e25-4075-ac7a-4d28b102745f">

**Comment by tani** [comment]
Your point is the expected behavior. It is not a problem.

**Comment by tani** [comment]
This issue is solved.
You can use `join()` to concatenate all strings.

**Comment by peacock0803sz** [comment]
Thank you for chatting in vim-jp slack, It's my lack of understanding for Vim script...

With `.vimrc` like this, it works correctly ~~ Then I'll make a PR to share this tips :)

```vimrc
let s:stylesheet =<< trim END
html, body, #viewer, #root {
  border: none;
  margin: 0.5rem;
  font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif !important;
}
END
let g:glance#stylesheet = join(s:stylesheet, "\n")
```
